### ISSUE TITLE
issue with ENOENT

### ISSUE THREAD

**Issue by codacy20** [alexellis/phantomjs-docker#1]
hey im trying to run this in a docker container and i got lucky, i saw your dockerfile which fixed lots of my errors but i still have a error regarding the ENOENT. 
do you know how i could overcome this?

thanks in advance

**Comment by alexellis** [comment]
Hi I'd need to see your fork, the changes you made and how you're running it.

Alex

**Comment by codacy20** [comment]
hey Alex thanks for the response. i fixed it. it was my mistake while installing the libraries. 
i was installing the libs on a image and then i was copying files to another image, therefor the libs that installed was wasted. stupid mistake if you ask me :) 

`
FROM node:10-slim AS builderino

ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN

WORKDIR /app

COPY .npmrc /app
COPY package.json /app
COPY package-lock.json /app
RUN apt-get update
RUN apt-get install -y apt-utils && apt-get install -y bzip2 
RUN npm install

COPY . /app
RUN npm run build
RUN npm run docs
RUN npm test
RUN npm prune --production

FROM node:10-slim as runner

ENV NO_UPDATE_NOTIFIER=1

WORKDIR /app
RUN apt-get update
RUN apt-get install -y libfontconfig

USER node

COPY --from=builderino app/dist /app/dist
COPY --from=builderino app/node_modules /app/node_modules/
COPY --from=builderino app/package.json /app/

CMD ["npm", "start"]
`
